Repository lmmentel/mendeleev, pull requests merged in 2024-05, with the labels that each got.

#121 Defer loading element data until attribute access
  mendeleev/__init__.py
  mendeleev/elements.py
Labels: enhancement, maintenance, performance

#148 Fix import error
  mendeleev/__init__.py
Labels: bugfix

#151 Add data export to various formats
  docs/source/data_access.rst
  poetry.lock
  pyproject.toml
  tasks.py
Labels: enhancement

#156 Create metadata table for stored properties
  README.md
  alembic/versions/7d745d77a7c1_add_propertymetadata_table.py
  docs/source/api/mendeleev.cli.rst
  docs/source/api/mendeleev.ion.rst
  docs/source/api/mendeleev.models.rst
  docs/source/api/models.rst
  docs/source/data.rst
  docs/source/data_access.rst
  docs/source/references.bib
  mendeleev/elements.db
  mendeleev/fetch.py
  mendeleev/models.py
Labels: enhancement
