Repository lmmentel/mendeleev, pull requests merged in 2024-06, with the labels that each got.

#160 Update Isotope.half_life_unit values
  mendeleev/elements.db
  tests/test_isotope.py
Labels: enhancement, data

#164 Add Mendeleev.jl to README
  README.md
Labels: documentation

#165 Use read-only SQLite connection
  mendeleev/db.py
Labels: bugfix
